name = "GBGraph"
uuid = "505cbe49-400a-43ab-9ef0-5ffc666d40c3"
authors = ["Wimmerer <wrkimmerer@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
